# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0147561b483c0ac0ff5348737910907c9806df5d0a32bed661efe3ea9052eac95aecfa0e79e7e7ccbb1d28ee70d6a253ab6ed11f01ed2d3ca7b2d30a8655392b

test:
  secret_key_base: 8b29cb048868a7639980a1f50e7b38603a325af6eb3ed6e96aabccd7fd50a4e2d214486839d622812743471dff9da917ac89860f0d57a422a21ed07d3bb80a97

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
